"""empty message

Revision ID: 008616e90a64
Revises: e391d87b93ba
Create Date: 2022-08-23 16:06:06.370530

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '008616e90a64'
down_revision = 'e391d87b93ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', mysql.VARCHAR(length=128), nullable=False))
    # ### end Alembic commands ###
